<a href="https://colab.research.google.com/github/syx1990/deep-learning/blob/main/all.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf

import numpy as np

# 输出版本号
print(tf.__version__)
# where 的使用
a = tf.constant([1,2,3,1,1])
b=tf.constant([0,1,3,4,5])
c = tf.where(tf.greater(a,b),a,b) # 若a>b，返回a对应位置的元素，否则返回b对应位置的元素
print("元素对比c:",c)
# 返回随机数
rdm = np.random.RandomState(seed=1) #seed=常数每次生成随机数相同
a1 = rdm.rand() # 返回一个随机标量
b1 = rdm.rand(2,3) # 返回维度为2行3列随机数矩阵
print("返回随机标量a:",a1)
print("返回随机数矩阵b:",b1)
# 将两个数组按垂直方向叠加
a2 = np.array([1,2,3])
b2 = np.array([4,5,6])
c2 = np.vstack((a2,b2))
print("将两个数组按垂直方向叠加c2:\n",c2)
# np.mgrid[ 起始值 : 结束值 : 步长 ，起始值 : 结束值 : 步长 , … ] 
# x.ravel( ) 将x变为一维数组，“把 . 前变量拉直”
# np.c_[ ] 使返回的间隔数值点配对
x,y = np.mgrid[1:3:1,2:4:0.5]
grid = np.c_[x.ravel(),y.ravel()]
print("一维数组x:",x)
print("一维数组y:",y)
print("返回的间隔数值点配对grid:\n",grid)



#激活函数

#对于初学者的建议：
# 首选relu激活函数；
# 学习率设置较小值；
# 输入特征标准化，即让输入特征满足以0为均值，
# 1为标准差的正态分布；
# 初始参数中心化，即让随机生成的参数满足以0
# 为均值， 2
# 当前层输入特征个数 为标准差的正态分布。


2.6.0
元素对比c: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
返回随机标量a: 0.417022004702574
返回随机数矩阵b: [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]
将两个数组按垂直方向叠加c2:
 [[1 2 3]
 [4 5 6]]
一维数组x: [[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
一维数组y: [[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]
返回的间隔数值点配对grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
