<a href="https://colab.research.google.com/github/syx1990/deep-learning/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# -*- coding: utf-8 -*-
# !/usr/bin/python3
# author by : yuxiangShi
# tell  by: 18538187569
# desc by: 基础知识记录和回顾

# 导入需要的包
import tensorflow as tf
import numpy as np

# 输出版本号
print(tf.__version__)

# 张量（Tensor）:多维数组（列表） 阶：张量的维数，张量可以表示0阶到n阶数组（列表）

# 维数 阶 名字 例子
# 0-D 0 标量 scalar s=1 2 3
# 1-D 1 向量 vector v=[1, 2, 3]
# 2-D 2 矩阵 matrix m=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# n-D n 张量 tensor t=[ [ [
# n个

# 数据类型
# tf.int, tf.float
#tf.int 32, tf.float 32, tf.float 64
# tf.bool
# tf.constant([True, False])
# tf.string
# tf.constant(“Hello, world!”)

# 创建一个张量
a = tf.constant([1,5],dtype=tf.int64)
print("输出张量的内容：",a)
print("输出张量的类型：",a.dtype)
print("输出张量的形状：",a.shape)

# 将numpy类型转换成Tensor(张量)
b = np.arange(0,5)
c= tf.convert_to_tensor(b,dtype=tf.int64)
print("输出numpy类型：",b)
print("将numpy类型转换成Tensor：",c)

#创建全为0的张量
#tf. zeros(维度) 创建全为1的张量
#tf. ones(维度) 创建全为指定值的张量
#tf. fill(维度，指定值)
#维度：
#一维 直接写个数
#二维 用 [行，列]
#多维 用 [n,m,j,k……]

# 案例
e = tf.zeros([2,3])
f = tf.ones(4)
g = tf.fill([2,2],9)

print("创建一个两行三列的张量：",e)
print("创建四行为1的张量：",f)
print("创建两行两例为9的张量：",g)

# 生成正态分布的随机数，默认均值为0，标准差为1
# tf. random.normal (维度，mean=均值，stddev=标准差) 生成截断式正态分布的随机数
# tf. random.truncated_normal (维度，mean=均值，stddev=标准差) 在tf.truncated_normal中如果随机生成数据的取值在（μ-2σ，μ+2σ）之外
# 则重新进行生成，保证了生成值在均值附近。
# μ：均值， σ：标准差

d1 = tf.random.normal([2,2],mean=0.5,stddev=1)
print("生成截断式正态分布的随机数:",d1)

e1 = tf.random.truncated_normal([2,2],mean=0.5,stddev=1)
print("生成值在均值附近的正态分布的随机数:",e1)

# 生成均匀分布随机数 [ minval, maxval )
# tf. random. uniform(维度，minval=最小值，maxval=最大值)

f1 = tf.random.uniform([2,2],minval=0,maxval=1)

print("生成均匀分布随机数:",f1)

# 常用函数
# 强制tensor转换为该数据类型
# tf.cast (张量名，dtype=数据类型) 计算张量维度上元素的最小值
# tf.reduce_min (张量名) 计算张量维度上元素的最大值
# tf.reduce_max (张量名)
# 理解axis
# 在一个二维张量或数组中，可以通过调整 axis 等于0或1 控制执行维度。
# axis=0代表跨行（经度，down)，而axis=1代表跨列（纬度，across)
# 如果不指定axis，则所有元素参与计算。
#  计算张量沿着指定维度的平均值
# tf.reduce_mean (张量名，axis=操作轴)  计算张量沿着指定维度的和
# tf.reduce_sum (张量名，axis=操作轴)

x1 = tf.constant([1,2,3],dtype=tf.float64)
print("输出x1的结果：",x1)

x2 = tf.cast(x1,tf.int32)
print("强制转换成整型：",x2)
print("取出最小的值：",tf.reduce_min(x2))
print("取出最大的值：",tf.reduce_max(x2))

# 计算张量沿着指定维度的平均值
x = tf.constant([[1,2,3],[2,2,3]])
print("输出x的结果:",x)
print("求x的平均值:",tf.reduce_mean(x))
print("求x的总和:",tf.reduce_sum(x,axis=1))

# tf.Variable () 将变量标记为“可训练”，被标记的变量会在反向传播
# 中记录梯度信息。神经网络训练中，常用该函数标记待训练参数。

w = tf.Variable(tf.random.normal([2,2],mean=0,stddev=1))

print("可训练的：",w)

# TensorFlow中的数学运算

# 对应元素的四则运算：tf.add，tf.subtract，tf.multiply，tf.divide
# 平方、次方与开方： tf.square，tf.pow，tf.sqrt
# 矩阵乘：tf.matmul
# 实现两个张量的对应元素相加
# tf.add (张量1，张量2)
# 实现两个张量的对应元素相减
# tf.subtract (张量1，张量2)
# 实现两个张量的对应元素相乘
# tf.multiply (张量1，张量2)
# 实现两个张量的对应元素相除
# tf.divide (张量1，张量2)
# 只有维度相同的张量才可以做四则运算

a1 = tf.ones([1,3]) # 生成1行3列为1的张量
b1 = tf.fill([1,3],3.) # 生成1行3列未3的张量

print("张量相加：",tf.add(a1,b1))
print("张量相减：",tf.subtract(a1,b1))
print("张量相乘：",tf.multiply(a1,b1))
print("张量相除：",tf.divide(a1,b1))

# 计算某个张量的平方
# tf.square (张量名) 
# 计算某个张量的n次方
# tf.pow (张量名，n次方数)
# 计算某个张量的开方
# tf.sqrt (张量名）

a3 = tf.fill([1,2],3.)

print("a3的值：",a3)

print("求a3的平方：",tf.square(a3))
print("求a3的次方：",tf.pow(a3,3))
print("求a3的开方：",tf.sqrt(a3))

# 实现两个矩阵的相乘
# tf.matmul(矩阵1，矩阵2)

a4 = tf.ones([3,2])
print(a4)
b4 = tf.fill([2,3],3.)
print(b4)
print("两个矩阵的相乘:",tf.matmul(a4,b4))

# 切分传入张量的第一维度，生成输入特征/标签对，构建数据集
# data = tf.data.Dataset.from_tensor_slices((输入特征, 标签))
#（Numpy和Tensor格式都可用该语句读入数据）

features = tf.constant([12,23,10,17])
labels = tf.constant([0,1,1,0])

dataset = tf.data.Dataset.from_tensor_slices((features, labels))
for element in dataset:
    print(element) # 打印不出结果

# tf.GradientTape
# with结构记录计算过程，gradient求出张量的梯度

with tf.GradientTape() as tape:
  # 计算过程
  w = tf.Variable(tf.constant(3.0))
  loss = tf.pow(w,2)
grad = tape.gradient(loss,w)
print("对w进行求导：",grad)

# enumerate是python的内建函数，它可遍历每个元素(如列表、元组或字符串)，组合为：索引 元素，常在for循环中使用。

seq = ['one','two','three']

for i,element in enumerate(seq):
  print("enumerate的使用：",i,element)

# tf.one_hot 独热编码（one-hot encoding）：在分类问题中，常用独热码做标签，标记类别：1表示是，0表示非。

#（ 0狗尾草鸢尾 1杂色鸢尾 2弗吉尼亚鸢尾 ） 标 签： 1
# 独热码： （0. 1. 0.）
# tf.one_hot()函数将待转换数据，转换为one-hot形式的数据输出。
# tf.one_hot (待转换数据, depth=几分类)

classes = 3

labels = tf.constant([1,0,2]) #  输入的元素值最小为0，最大为2
output = tf.one_hot(labels,depth=classes)

print("one_hot:",output)

# sotfmax 使输出符合概率分布

y = tf.constant([1.01,2.01,-0.66])

y_pro = tf.nn.softmax(y)

print("After softmax, y_pro is:", y_pro)

# assign_sub 
# 赋值操作，更新参数的值并返回。
# w.assign_sub (w要自减的内容)

w1 = tf.Variable(4)
w1.assign_sub(1)
print("赋值操作：",w1)

# tf.argmax
# 返回张量沿指定维度最大值的索引
# tf.argmax (张量名,axis=操作轴)

test = np.array([[1,2,3],[2,3,4],[8,7,2]])

print("输出数组类型：",test)

print(tf.argmax(test,axis=0)) # 返回每一列（经度）最大值的索引
print(tf.argmax(test,axis=1)) # 返回每一行（纬度）最大值的索引

2.6.0
输出张量的内容： tf.Tensor([1 5], shape=(2,), dtype=int64)
输出张量的类型： <dtype: 'int64'>
输出张量的形状： (2,)
输出numpy类型： [0 1 2 3 4]
将numpy类型转换成Tensor： tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
创建一个两行三列的张量： tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
创建四行为1的张量： tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
创建两行两例为9的张量： tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)
生成截断式正态分布的随机数: tf.Tensor(
[[0.11348999 0.44555753]
 [0.32937184 0.45427614]], shape=(2, 2), dtype=float32)
生成值在均值附近的正态分布的随机数: tf.Tensor(
[[0.3060819 1.6184272]
 [0.6121552 0.3950799]], shape=(2, 2), dtype=float32)
生成均匀分布随机数: tf.Tensor(
[[0.30975783 0.8702085 ]
 [0.5135678  0.16523707]], shape=(2, 2), dtype=float32)
输出x1的结果： tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
强制转换成整型： tf.Tensor([1 2 3], shape=(3,), dtype=int32)
取出最小的值： tf.Tensor(1, shape=(), dtype=int32)
取出最大的值： tf.Tensor(3, shape=(), dtype=int32)
输出x的结果: tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
求x的平均值: tf.Tensor(2, s